import org.kuali.ole.deliver.bo.OleDroolsHoldResponseBo
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.form.OLEPlaceRequestForm;

rule "pickup-location-based-on-patron-type"
agenda-group "pickup-location"
activation-group "pickup-location"

when

 
 $pr : OLEPlaceRequestForm(getItemType() in ("LONG","ONE_WEEK","THREE_DAYS","REF") , getItemLocation() in ("MAIN","EGHAM","RAINHAM","Level E"))
 $d : DroolsResponse()

then
 
 $d.setRuleMatched(true);
 $pr.setPickUpLocation("SOAS_MAIN");


 end

