import org.kuali.ole.deliver.bo.OleDroolsHoldResponseBo
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.form.OLEPlaceRequestForm;

rule "pickup-location-based-on-patron-type"
agenda-group "pickup-location"
activation-group "pickup-location"

when

 
 $pr : OLEPlaceRequestForm(getItemType() in ("LONG","ONE_WEEK") , getItemLocation() in ("MAIN","EGHAM","DAGENHAM"))

then
 $pr.setPickUpLocation("SOAS_MAIN");


 end

