package org.kuali.ole.deliver.rules.chicago.ncip
import org.kuali.ole.deliver.bo.OleDeliverRequestBo
import org.kuali.ole.deliver.bo.OleDroolsHoldResponseBo
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.util.NoticeInfo
import org.kuali.ole.deliver.drools.DroolsConstants

rule "2W_1M_6W_3MLoanRecallRequest_new"
agenda-group "place-request"
when
$n: NoticeInfo()
$d : DroolsResponse()
$dr: OleDeliverRequestBo(getItemType() in ("LONG"),!isClaimsReturnedFlag(),
getRequestTypeCode() in ("Recall/Hold Request"))
$p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"),getRequestedItemRecordsCount()<3,$dr!=null,getLoanedPatronBorrowerType($dr.getItemId()) not in ("ILL"))

then
$d.setRuleMatched(true);
$n.setNoticeType(OLEConstants.NOTICE_RECALL);
$d.getDroolsExchange().addToContext("requestExpirationDays",90);
$d.getDroolsExchange().addToContext("minimumLoanPeriod","0-D");
$d.getDroolsExchange().addToContext("recallLoanPeriod","7-D");
$d.getDroolsExchange().addToContext(OLEConstants.RECALL_NOTICE_CONTENT_CONFIG_NAME,"recall-notice");
$d.getDroolsExchange().addToContext(OLEConstants.REQUEST_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"Request Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_NOTICE_CONTENT_CONFIG_NAME,"On Hold Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"On Hold Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_COURTESY_NOTICE_CONTENT_CONFIG_NAME,"On Hold Courtesy Notice");
 end

rule "2W_1M_6W_3MLoanRecallRequest_new1"
agenda-group "place-request"
when
$n: NoticeInfo()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"),getRequestedItemRecordsCount()<3)
$i: OleDeliverRequestBo(getItemType() in ("LONG"),isClaimsReturnedFlag(),
getRequestTypeCode() in ("Recall/Hold Request"))

then
$d.setRuleMatched(true);
$d.addErrorMessage("Item has been claimed as returned. So item is temporarily unavailable for circulation.");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);

 end


rule "2W_1M_6W_3MLoanRecallRequest_new2"
agenda-group "place-request"
when
$n: NoticeInfo()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"),getRequestedItemRecordsCount()>=3)
$i: OleDeliverRequestBo(getItemType() in ("LONG"),
getRequestTypeCode() in ("Recall/Hold Request"))

then
$d.setRuleMatched(true);
$d.addErrorMessage("The patron has reached the maximum Request limit");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
 end


rule "2W_1M_6W_3MLoanRecallRequest_new3"
agenda-group "place-request"
when
$n: NoticeInfo()
$d : DroolsResponse()
$dr: OleDeliverRequestBo(getItemType() in ("LONG"),
getRequestTypeCode() in ("Recall/Hold Request"))
$p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"), $dr!=null,getLoanedPatronBorrowerType($dr.getItemId()) in ("ILL"))

then
$d.setRuleMatched(true);
$d.addErrorMessage("Items on LOAN to ILL patrons CANT be 'requested' (Recalled or OnHOLD)");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
 end


rule "One_Week_LoanRecalRequest_new"
agenda-group "place-request"
when
$n: NoticeInfo()
$d : DroolsResponse()
$dr: OleDeliverRequestBo(getItemType() in ("ONE_WEEK"),!isClaimsReturnedFlag(),getRequestTypeCode() in ("Recall/Hold Request"))
$p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"),getRequestedItemRecordsCount() < 3,
$dr!=null,getLoanedPatronBorrowerType($dr.getItemId()) not in ("ILL"))


then
$d.setRuleMatched(true);
$n.setNoticeType(OLEConstants.NOTICE_RECALL);
$d.getDroolsExchange().addToContext("requestExpirationDays",90);
$d.getDroolsExchange().addToContext("minimumLoanPeriod","0-D");
$d.getDroolsExchange().addToContext("recallLoanPeriod","7-D");
$d.getDroolsExchange().addToContext(OLEConstants.RECALL_NOTICE_CONTENT_CONFIG_NAME,"recall-notice");
$d.getDroolsExchange().addToContext(OLEConstants.REQUEST_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"Request Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_NOTICE_CONTENT_CONFIG_NAME,"On Hold Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"On Hold Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_COURTESY_NOTICE_CONTENT_CONFIG_NAME,"On Hold Courtesy Notice");
 end

rule "One_Week_LoanRecalRequest_new1"
agenda-group "place-request"
when
$n: NoticeInfo()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"),getRequestedItemRecordsCount() < 3)
$i: OleDeliverRequestBo(getItemType() in ("ONE_WEEK"),isClaimsReturnedFlag(),
getRequestTypeCode() in ("Recall/Hold Request"))

then
$d.setRuleMatched(true);
$d.addErrorMessage("Item has been claimed as returned. So item is temporarily unavailable for circulation.");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);

 end

 rule "One_Week_LoanRecalRequest_new2"
 agenda-group "place-request"
 when
 $n: NoticeInfo()
 $d : DroolsResponse()
 $p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"),getRequestedItemRecordsCount() >= 3)
 $i: OleDeliverRequestBo(getItemType() in ("ONE_WEEK"),
 getRequestTypeCode() in ("Recall/Hold Request"))

 then
 $d.setRuleMatched(true);
 $d.addErrorMessage("The patron has reached the maximum Request limit");
 $d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);

  end

 rule "One_Week_LoanRecalRequest_new3"
 agenda-group "place-request"
 when
 $n: NoticeInfo()
 $d : DroolsResponse()
 $i: OleDeliverRequestBo(getItemType() in ("ONE_WEEK"),
 getRequestTypeCode() in ("Recall/Hold Request"))
 $p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"),$i!=null,getLoanedPatronBorrowerType($i.getItemId()) in ("ILL"))
 
 then
 $d.setRuleMatched(true);
 $d.addErrorMessage("Items on LOAN to ILL patrons CANT be 'requested' (Recalled or OnHOLD)");
 $d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
  end

rule "2W_1M_6W_3MLoanHoldRequest"
  agenda-group "place-request"
  when
  $n: NoticeInfo()
  $d : DroolsResponse()
  $dr: OleDeliverRequestBo(getItemType() in ("LONG","ONE_WEEK"),!isClaimsReturnedFlag(),
  getRequestTypeCode() in ("Hold/Hold Request"))
  $p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"),getRequestedItemRecordsCount()<3,$dr!=null,getLoanedPatronBorrowerType($dr.getItemId()) not in ("ILL"))

  then
  $d.setRuleMatched(true);
  $d.getDroolsExchange().addToContext("requestExpirationDays",90);
$d.getDroolsExchange().addToContext(OLEConstants.RECALL_NOTICE_CONTENT_CONFIG_NAME,"recall-notice");
$d.getDroolsExchange().addToContext(OLEConstants.REQUEST_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"Request Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_NOTICE_CONTENT_CONFIG_NAME,"On Hold Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"On Hold Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_COURTESY_NOTICE_CONTENT_CONFIG_NAME,"On Hold Courtesy Notice");
   end

  rule "2W_1M_6W_3MLoanHOLDRequest1"
  agenda-group "place-request"
  when
  $n: NoticeInfo()
  $d : DroolsResponse()
  $i: OleDeliverRequestBo(getItemType() in ("LONG","ONE_WEEK"),isClaimsReturnedFlag(),
  getRequestTypeCode() in ("Hold/Hold Request"))
  $p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"),getRequestedItemRecordsCount()<3)


  then
  $d.setRuleMatched(true);
  $d.addErrorMessage("Item has been claimed as returned. So item is temporarily unavailable for circulation.");
  $d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);

   end


  rule "2W_1M_6W_3MLoanHoldRequest2"
  agenda-group "place-request"
  when
  $n: NoticeInfo()
  $d : DroolsResponse()
  $p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"),getRequestedItemRecordsCount()>=3)
  $i: OleDeliverRequestBo(getItemType() in ("LONG","ONE_WEEK"),
  getRequestTypeCode() in ("Hold/Hold Request"))

  then
  $d.setRuleMatched(true);
  $d.addErrorMessage("The patron has reached the maximum Request limit");
  $d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
   end

rule "2W_1M_6W_3MLoanHoldRequest5"
  agenda-group "place-request"
  when
  $n: NoticeInfo()
  $d : DroolsResponse()
  $dr: OleDeliverRequestBo(getItemType() in ("LONG","ONE_WEEK"),
  getRequestTypeCode() in ("Hold/Hold Request"))
  $p: OlePatronDocument(getBorrowerTypeCode() in ("STU","STUX","FULLX","FULL","ALUMNI","EXT","SCHLR"),$dr!=null,getLoanedPatronBorrowerType($dr.getItemId()) in ("ILL"))

  then
  $d.setRuleMatched(true);
  $d.addErrorMessage("Items on LOAN to ILL patrons CANT be 'requested' (Recalled or OnHOLD)");
  $d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION); 

   end


 rule "2W_1M_6W_3MLoanHoldRequest3"
  agenda-group "place-request"
  when
  $n: NoticeInfo()
  $d : DroolsResponse()
  $p: OlePatronDocument(getBorrowerTypeCode() in ("ILL"))
  $dr: OleDeliverRequestBo(getItemType() in ("LONG","ONE_WEEK"),!isClaimsReturnedFlag(),
  getRequestTypeCode() in ("Hold/Hold Request"))

  then
  $d.setRuleMatched(true);
  $d.getDroolsExchange().addToContext("requestExpirationDays",90);
$d.getDroolsExchange().addToContext(OLEConstants.RECALL_NOTICE_CONTENT_CONFIG_NAME,"recall-notice");
$d.getDroolsExchange().addToContext(OLEConstants.REQUEST_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"Request Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_NOTICE_CONTENT_CONFIG_NAME,"On Hold Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"On Hold Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_COURTESY_NOTICE_CONTENT_CONFIG_NAME,"On Hold Courtesy Notice");
   end

  rule "2W_1M_6W_3MLoanHOLDRequest4"
  agenda-group "place-request"
  when
  $n: NoticeInfo()
  $d : DroolsResponse()
  $p: OlePatronDocument(getBorrowerTypeCode() in ("ILL"))
  $i: OleDeliverRequestBo(getItemType() in ("LONG","ONE_WEEK"),isClaimsReturnedFlag(),
  getRequestTypeCode() in ("Hold/Hold Request"))

  then
  $d.setRuleMatched(true);
  $d.addErrorMessage("Item has been claimed as returned. So item is temporarily unavailable for circulation.");
  $d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);

   end


 rule "2W_1M_6W_3MLoanHoldRequestLIB1"
  agenda-group "place-request"
  when
  $n: NoticeInfo()
  $d : DroolsResponse()
  $p: OlePatronDocument(getBorrowerTypeCode() in ("LIB"))
  $dr: OleDeliverRequestBo(getItemType() in ("LONG","ONE_WEEK"),!isClaimsReturnedFlag(),
  getRequestTypeCode() in ("Hold/Hold Request","Recall/Hold Request"))

  then
  $d.setRuleMatched(true);
  $d.getDroolsExchange().addToContext("requestExpirationDays",90);
$d.getDroolsExchange().addToContext(OLEConstants.RECALL_NOTICE_CONTENT_CONFIG_NAME,"recall-notice");
$d.getDroolsExchange().addToContext(OLEConstants.REQUEST_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"Request Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_NOTICE_CONTENT_CONFIG_NAME,"On Hold Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"On Hold Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_COURTESY_NOTICE_CONTENT_CONFIG_NAME,"On Hold Courtesy Notice");
   end

 rule "2W_1M_6W_3MLoanHoldRequestLIB2"
  agenda-group "place-request"
  when
  $n: NoticeInfo()
  $d : DroolsResponse()
  $p: OlePatronDocument(getBorrowerTypeCode() in ("LIB"))
  $dr: OleDeliverRequestBo(getItemType() in ("LONG","ONE_WEEK"),isClaimsReturnedFlag(),
  getRequestTypeCode() in ("Hold/Hold Request"))

  then
  $d.setRuleMatched(true);
  $d.addErrorMessage("Item has been claimed as returned. So item is temporarily unavailable for circulation.");
  $d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);

   end

 rule "2W_1M_6W_3MLoanRecallRequestLIB2"
  agenda-group "place-request"
  when
  $n: NoticeInfo()
  $d : DroolsResponse()
  $p: OlePatronDocument(getBorrowerTypeCode() in ("LIB"))
  $dr: OleDeliverRequestBo(getItemType() in ("LONG","ONE_WEEK"),!isClaimsReturnedFlag(),
  getRequestTypeCode() in ("Recall/Hold Request"))

  then
  $d.setRuleMatched(true);
  $d.getDroolsExchange().addToContext("requestExpirationDays",90);
$d.getDroolsExchange().addToContext("minimumLoanPeriod","0-D");
$d.getDroolsExchange().addToContext("recallLoanPeriod","7-D");
$d.getDroolsExchange().addToContext(OLEConstants.RECALL_NOTICE_CONTENT_CONFIG_NAME,"recall-notice");
$d.getDroolsExchange().addToContext(OLEConstants.REQUEST_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"Request Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_NOTICE_CONTENT_CONFIG_NAME,"On Hold Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_EXPIRATION_NOTICE_CONTENT_CONFIG_NAME,"On Hold Expiration Notice");
$d.getDroolsExchange().addToContext(OLEConstants.ON_HOLD_COURTESY_NOTICE_CONTENT_CONFIG_NAME,"On Hold Courtesy Notice");
   end





