package org.kuali.ole.deliver.checkin


import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.drools.DroolsConstants


 rule "On-Hold for pickup"
agenda-group "checkin-validation-for-loan"
activation-group "checkin-validation-for-loan"


when

$i: OleItemRecordForCirc($r:getOleDeliverRequestBo(), null!= $r, $r.getRequestTypeCode() in ("Recall/Hold Request", "Hold/Hold Request"))

$d : DroolsResponse()

then
$i.setItemStatusToBeUpdatedTo("ONHOLD");
$i.updateCheckinCount();
$d.getDroolsExchange().addToContext(DroolsConstants.PRINT_SLIP_FLAG, true);
$d.setRuleMatched(true);
 end
