package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.DroolsResponse


rule "1MLCheckOutValidationNew1"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("EXT"),getTotalLoanedItemsCount() < 3)
$i: OleItemRecordForCirc(getItemType() in ("LONG"))

then
$l.setCirculationPolicyId("1MLCheckOutValidationNew1");
$l.loanPeriod("30-D","7-D");
 end

rule "1MLCheckOutValidationNew2"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("EXT"),getTotalLoanedItemsCount() >= 3)
$i: OleItemRecordForCirc(getItemType() in ("LONG"))

then
$l.setCirculationPolicyId("1MLCheckOutValidationNew2");
$d.addErrorMessage("Patron has more than 3 items checked out");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.loanPeriod("30-D","7-D");
 end

rule "1MLCheckOutValidationNew11"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("STUX"),getTotalLoanedItemsCount() < 25)
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
$l.setCirculationPolicyId("1MLCheckOutValidationNew11");
$l.loanPeriod("30-D","7-D");
 end

rule "1MLCheckOutValidationNew12"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("STUX"),getTotalLoanedItemsCount() >= 25)
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
$l.setCirculationPolicyId("1MLCheckOutValidationNew12");
$d.addErrorMessage("Patron has more than 25 items checked out");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.loanPeriod("30-D","7-D");
 end

rule "1MLCheckOutValidationNew13"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("SCHLR"),getTotalLoanedItemsCount() < 50)
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
$l.setCirculationPolicyId("1MLCheckOutValidationNew13");
$l.loanPeriod("30-D","7-D");
 end

rule "1MLCheckOutValidationNew14"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("SCHLR"),getTotalLoanedItemsCount() >= 50)
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
$l.setCirculationPolicyId("1MLCheckOutValidationNew14");
$d.addErrorMessage("Patron has more than 50 items checked out");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.loanPeriod("30-D","7-D");
 end

rule "1MLCheckOutValidationNewAlumni1"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("ALUMNI"),getTotalLoanedItemsCount() < 6)
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
$l.setCirculationPolicyId("1MLCheckOutValidationNewAlumni1");
$l.loanPeriod("30-D","7-D");
 end

rule "1MLCheckOutValidationNewAlumni2"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("ALUMNI"),getTotalLoanedItemsCount() >= 6)
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
$l.setCirculationPolicyId("1MLCheckOutValidationNewAlumni2");
$d.addErrorMessage("Patron has more than 6 items checked out");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.loanPeriod("30-D","7-D");
 end
