package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.DroolsResponse

rule "6WLCheckOutValidation1"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("ILL"),getTotalLoanedItemsCount() < 100)
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
$l.setCirculationPolicyId("6WLCheckOutValidation1");
$l.loanPeriod("42-D","7-D");
 end


rule "6WLCheckOutValidation2"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("ILL"),getTotalLoanedItemsCount() >= 100)
$i: OleItemRecordForCirc (getItemType() in ("LONG"))


then
$l.setCirculationPolicyId("6WLCheckOutValidation2");
$d.addErrorMessage("Patron has more than 100 items checked out");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.loanPeriod("42-D","7-D");
 end
