package org.kuali.ole.deliver.checkout

import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.util.ErrorMessage
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.drools.DroolsConstants


rule "2WLCheckOutNew1"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d: DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("STU"),getTotalLoanedItemsCount() < 20)
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
$l.setCirculationPolicyId("2WLCheckOutNew1");
$l.loanPeriod("14-D","7-D");
 end

rule "2WLCheckOutNew2"
agenda-group "checkout validation"
activation-group "checkout validation"
when
$l: OleLoanDocument()
$d: DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("STU"),getTotalLoanedItemsCount() >= 20)
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
$l.setCirculationPolicyId("2WLCheckOutNew2");
$d.addErrorMessage("Patron has more than 20 items checked out");
$d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
$l.loanPeriod("14-D","7-D");
 end

