
import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.util.NoticeInfo

rule "MMRenewalValidation"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) < 10)
$d : DroolsResponse()
$n: NoticeInfo()
$p: OlePatronDocument()
$i: OleItemRecordForCirc (getItemType() in ("MM"), $z: getOleDeliverRequestBo(), null == $z)

then
 $d.setRuleMatched(true);
 $l.setCirculationPolicyId("MMRenewalValidation");
 $l.loanPeriod("7-D","7-D");
 $n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end

rule "MMRenewalValidation1"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) >= 10)
$n: NoticeInfo()
$d : DroolsResponse()
$p: OlePatronDocument()
$i: OleItemRecordForCirc (getItemType() in ("MM"))

then
 $d.setRuleMatched(true);
 $l.setCirculationPolicyId("MMRenewalValidation1");
 $d.addErrorMessage("Patron has more than allowed limit of renewals");
 $d.addErrorMessageCode("ErrorMessageFromRule");
 $d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
 $l.loanPeriod("7-D","7-D");
 $n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end
