package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.util.NoticeInfo

rule "ThreeMonthLoanRenewalNew"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) < 10)
$n: NoticeInfo()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FULL","SPORS","FULLX","RESAST"))
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
 $d.setRuleMatched(true);
 $l.setCirculationPolicyId("ThreeMonthLoanRenewalNew");
 $l.loanPeriod("90-D","7-D");
 $n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end

rule "ThreeMonthLoanRenewalNew1"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) >= 10)
$n: NoticeInfo()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FULL","SPORS","FULLX","RESAST"))
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
 $d.setRuleMatched(true);
 $l.setCirculationPolicyId("ThreeMonthLoanRenewalNew1");
 $d.addErrorMessage("Patron has more than allowed limit of renewals");
 $d.addErrorMessageCode("ErrorMessageFromRule");
 $d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
 $l.loanPeriod("90-D","90-D");
 $n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end

rule "ThreeMonthLoanRenewalNewLIB"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument()
$n: NoticeInfo()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("LIB"))
$i: OleItemRecordForCirc (getItemType() in ("LONG"))

then
 $d.setRuleMatched(true);
 $l.setCirculationPolicyId("ThreeMonthLoanRenewalNewLIB");
 $l.loanPeriod("90-D","7-D");
 end
