package org.kuali.ole.deliver.fines

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ItemFineRate
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.bo.PatronBillPayment
import org.kuali.ole.deliver.util.DroolsResponse


rule "overdueFineCalc3"
agenda-group "fine validation"
activation-group "fine validation"
when

$b: ItemFineRate()
$p: OlePatronDocument(getBorrowerTypeCode() not in ("REPAIRS"))
$i: OleItemRecordForCirc (getItemType() in ("CARREL"))
then
$b.setFineRate(3.0);
$b.setInterval("3-H");
end
